AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'bedrock-line-chat

  '
Parameters:
  LineChannelAccessToken:
    Type: String
  LineChannelSecret:
    Type: String
  NumOfHistory:
    Type: String
    Default: '10'
  FoundationModel:
    Type: String
    AllowedValues:
    - anthropic.claude-3-5-sonnet-20240620-v1:0
    - anthropic.claude-3-opus-20240229-v1:0
    - anthropic.claude-3-sonnet-20240229-v1:0
    - anthropic.claude-3-haiku-20240307-v1:0
    - anthropic.claude-v2:1
    Default: anthropic.claude-3-5-sonnet-20240620-v1:0
Globals:
  Function:
    Timeout: 120
    MemorySize: 512
Resources:
  LineBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverlessrepo-bedrock-line-chat/065fe008cf405bcbaddfc5132329e595
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN:
            Ref: LineChannelAccessToken
          LINE_CHANNEL_SECRET:
            Ref: LineChannelSecret
          NUM_OF_HISTORY:
            Ref: NumOfHistory
          FOUNDATION_MODEL:
            Ref: FoundationModel
          DYNAMODB_TABLE_NAME:
            Ref: DynamoDBTable
      Role:
        Fn::GetAtt:
        - LineBotFunctionRole
        - Arn
    Connectors:
      DynamoDBConnector:
        Properties:
          Destination:
            Id: DynamoDBTable
          Permissions:
          - Read
          - Write
    Metadata:
      SamResourceId: LineBotFunction
  LineBotFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: LineBotFunctionRolePolicy0
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: bedrock:*
            Resource: '*'
    Metadata:
      SamResourceId: LineBotFunctionRole
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: SessionId
        AttributeType: S
      KeySchema:
      - AttributeName: SessionId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: DynamoDBTable
Outputs:
  FunctionUrl:
    Value:
      Fn::GetAtt: LineBotFunctionUrl.FunctionUrl
